ProjetoTop/Models/ErrorViewModel.cs
namespace ProjetoTop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoTop/Models/Produto.cs
namespace ProjetoTop.Models
{
    public class Produto
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public decimal Preco { get; set; }
        public int Quantidade { get; set; }
    }
}

ProjetoTop/Models/Usuario.cs
namespace ProjetoTop.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
    }
}

ProjetoTop/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ProjetoTop.Models;

namespace ProjetoTop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoTop/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using MySqlX.XDevAPI;
using ProjetoTop.Models;
using ProjetoTop.Repositorio;

namespace ProjetoTop.Controllers
{
    public class ProdutoController : Controller
    {

        private readonly ProdutoRepositorio _produtoRepositorio;

        public ProdutoController(ProdutoRepositorio produtoRepositorio)
        {
            _produtoRepositorio = produtoRepositorio;
        }

        public IActionResult Index()
        {
            return View(_produtoRepositorio.TodosProdutos());
        }

        public IActionResult CadastrarProduto()
        {
            return View();
        }
        [HttpPost]

        public IActionResult CadastrarProduto(Produto produto)
        {

            _produtoRepositorio.CadastrarProduto(produto);

            return RedirectToAction(nameof(CadastrarProduto));
        }

        public IActionResult EditarProduto(int id)
        {
           
            var produto = _produtoRepositorio.ObterProduto(id);

            
            if (produto == null)
            {
                
                return NotFound();
            }

            
            return View(produto);
        }

        public IActionResult ExcluirProduto(int id)
        {
            _produtoRepositorio.ExcluirProduto(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

ProjetoTop/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoTop.Repositorio;

namespace ProjetoTop.Controllers
{
    public class UsuarioController : Controller
    {

        private readonly LoginRepositorio _loginRepositorio;

        public UsuarioController(LoginRepositorio loginRepositorio)
        {
            _loginRepositorio = loginRepositorio;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Login(string email, string senha) 
        {
            var usuario = _loginRepositorio.ObterUsuario(email);
            
            if (usuario != null && usuario.Senha == senha)
            {               
                return RedirectToAction("Index", "Cliente");
            }
            

            ModelState.AddModelError("", "Email ou senha inválidos.");
            
            return View();
        }
    }
}

ProjetoTop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link href="~/css/home.css" rel="stylesheet" />

<header>
    <video autoplay muted loop class="video-fundo">
        <source src="/Video/12620029_3840_2160_60fps.mp4" type="video/mp4" />

    </video>
    <div class="container text-center text-warning  ">
        <h1 class="">Sistema de Clientes</h1>
        <p class="">Tecnologia de Qualidade</p>
        <div>
            <button class="btn btn-outline-light me-2">Saiba Mais...</button>
        </div>

    </div>

</header>

ProjetoTop/Views/Produto/CadastrarProduto.cshtml
@model ProjetoTop.Models.Produto;

<link href="~/css/cadastraProd.css" rel="stylesheet" />

<h1 class="title-cli">Cadastrar Produto</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>

            <div class="btn">
                <div class="form-group">
                    <input type="submit" value="Cadastrar" class="btn btn-primary" />
                </div>
                <div class="form-group">
                    <a asp-action="Index" class="btn btn-success">Voltar</a>
                </div>
            </div>
        </form>
    </div>
</div>

ProjetoTop/Views/Produto/EditarProduto.cshtml
@model ProjetoTop.Models.Produto;

<h1>Editar Produto</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarProduto" method="post">
            
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Quantidade" class="control-label"></label>
                <input asp-for="Quantidade" class="form-control" />
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Alterar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="PainelProduto">Voltar</a>
</div>

ProjetoTop/Views/Produto/Index.cshtml
@model IEnumerable<ProjetoTop.Models.Produto>

<p>
    <a asp-controller="Produto" asp-action="CadastrarProduto">Cadastrar Produto</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>Ação</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Preco)
                </td>
                <td>
                    @Html.ActionLink("Editar", "EditarProduto", new { id = item.Id }) |
                    @Html.ActionLink("Excluir", "ExcluirProduto", new { id = item.Id },
                             new { onclick = "return confirm('Deseja realmente Excluir este item?');" })
                </td>
            </tr>
        }
    </tbody>
</table>

ProjetoTop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoTop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoTop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoTop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ProjetoTop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjetoTop/Views/Usuario/Login.cshtml
@model ProjetoTop.Models.Usuario;

<link href="~/css/login.css" rel="stylesheet" />

<h1 class="login-title">Login</h1>

<form asp-action="Login" method="post" class="login-form">
    <div class="form-group">
        <label>Email:</label>
        <input type="email" name="email" required class="form-control" />
    </div>
    <div class="form-group">
        <label>Senha:</label>
        <input type="password" name="senha" required class="form-control" />
    </div>
    <button type="submit" class="btn btn-secondary">Login</button>
</form>